### ISSUE TITLE
demo mode crashes

### ISSUE THREAD

**Issue by chaos5235** [ysoldak/fpvc-lady#6]
after a short time demo mode crashes

 ID | Name       | Description          | Updated      || Kills | Deaths | Lives
--- | ---------- | -------------------- | ------------ || ----- | ------ | ------
 A1 | ALICE      | fake fake fake fake  | 09:11:28.302 ||     0 |      5 |     0
 B1 | BARTOLOMEO | fake fake fake fake  | 09:11:29.302 ||     5 |      0 |   255
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
main.commentAction(0xc000054540)
        /home/runner/work/fpvc-lady/fpvc-lady/cmd/lady/comment.go:63 +0x3ad
github.com/urfave/cli/v2.(*Command).Run(0xc000172160, 0xc000054540, {0xc00002c3e0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x97d
github.com/urfave/cli/v2.(*App).RunContext(0xc000160200, {0xe2c660, 0x112c100}, {0xc00002c3e0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.2/app.go:307
main.main()
        /home/runner/work/fpvc-lady/fpvc-lady/cmd/lady/main.go:21 +0x419

goroutine 6 [chan receive]:
github.com/ysoldak/fpvc-lady/internal/tts.(*Tts).Run(...)
        /home/runner/work/fpvc-lady/fpvc-lady/internal/tts/tts.go:51
created by main.commentAction in goroutine 1
        /home/runner/work/fpvc-lady/fpvc-lady/cmd/lady/comment.go:26 +0xac

goroutine 8 [chan receive]:
main.trace()
        /home/runner/work/fpvc-lady/fpvc-lady/cmd/lady/trace.go:22 +0x12c
created by main.commentAction in goroutine 1
        /home/runner/work/fpvc-lady/fpvc-lady/cmd/lady/comment.go:51 +0x259

**Comment by ysoldak** [comment]
Shall be working now, with 0.4.0
